sudo: required

services:
  - docker

branches:
  only:
    - master

install:
  - docker build -t hnakamur/nginxrpm .

script:
  - docker run hnakamur/nginxrpm "$COPR_LOGIN" "$COPR_USERNAME" "$COPR_TOKEN"
